### PR TITLE
fixed login form

### PR DESCRIPTION
**Pull request by Aditya201551**
fixes for issue #179 

- fixed up login page
- made it responsive

@harshita2216

### CODE REVIEW

**Comment by Aditya201551** [comment]
Screenshot (87)

**Review by harshita2216 — CHANGES_REQUESTED** [review]
Please align the iframe properly.

**Comment by khanfarhan10** [comment]
Please resolve all merge conflicts in the css.

**Comment by Aditya201551** [comment]
@khanfarhan10 done!

**Review by harshita2216 — APPROVED** [review]

**Comment by ashutoshkrris** [comment]
Hey @Aditya201551 
Please check if you mistakenly removed this part from urls.py as it is necessary for Ajax validation of email and password field :
`path('validate-email/', csrf_exempt(email_validation), name='email_validate'),
    path('validate-password/', csrf_exempt(password_validation),
         name='password_validate'),`

**Pull request merged**
