### PR TITLE
Added View Image Button

### PR DESCRIPTION
**Pull request by sk1122**
- This PR Solves #79 
- Added a View Image Button which would show the uploaded image to the user
- It opens a new window
- It solves #79 in `http://localhost:8000/view_usernotes`

- Screenshot
sharenlearn

### CODE REVIEW

**Review by harshita2216 — CHANGES_REQUESTED** [review]
@sk1122 You were supposed to have a carousel preview and not redirect to another page. Please check #79 description. Also, make this for other files as well.

**Comment by sk1122** [comment]
Ohh, Sorry, I will work on that

**Comment by sk1122** [comment]
https://user-images.githubusercontent.com/40713709/113254581-69ca5a80-92e4-11eb-9cc7-f41b124c195e.mp4

Carousel

**Comment by sk1122** [comment]
carousel
Carousel for Uploaded Images

**Comment by sk1122** [comment]
@harshita2216 Any Updates?

**Pull request merged**
