### PR TITLE
issue 91- 10 digit contact number

### LINKED ISSUE #91: In sign up page :- Contact validation of 10 digit
In sign up form there should be  validation of 10 digit number . I want to work on this issue as a participate of gssoc21 .

### PR DESCRIPTION
**Pull request by kumarishalini6**
I have put the validation of 10 digit contact
fixes #91 
Share N Learn - Personal - Microsoft​ Edge 3_17_2021 06_03_51 PM
 number

### CODE REVIEW

**Review by harshita2216 — CHANGES_REQUESTED** [review]
The validation is not proper. The field is accepting - (negative) signs as well since the type of input is number.

**Comment by kumarishalini6** [comment]
Ok I'll check it again

**Comment by kumarishalini6** [comment]
I have checked , the validations  works properly in my system  and not accepting the negative number.

**Comment by amanjha8100** [comment]
Already approved your previous PR.

**Comment by kumarishalini6** [comment]
now you can check it . 
Share N Learn2
Share N Learn1

**Comment by harshita2216** [comment]
It is still signing up for negative numbers. Please check. @kumarishalini6

**Review by harshita2216 — CHANGES_REQUESTED** [review]
It is still signing up for negative numbers. Please check again. @kumarishalini6

**Comment by kumarishalini6** [comment]
i hope this time it works.
Share N Learn1
Share N Learn2

**Review by harshita2216 — APPROVED** [review]

**Pull request merged**
