### PR TITLE
Issue 91

### PR DESCRIPTION
**Pull request by kumarishalini6**
I have add the contact validation i.i, contact number should be of 10 digit.
Share N Learn - Personal - Microsoft​ Edge 3_17_2021 06_03_51 PM

### CODE REVIEW

**Review by amanjha8100 — CHANGES_REQUESTED** [review]
please keep your requirements.txt into .gitignore and submit PR once again. Sorry for late review.

**Comment by kumarishalini6** [comment]
Ok I'll do it

**Review by amanjha8100 — DISMISSED** [review]

**Comment by kumarishalini6** [comment]
when my PR get merged

**Review by amanjha8100 — COMMENTED** [review]
Harshita will talk to you!!

**Comment by amanjha8100** [comment]
Your another PR for same issue is under review, there has been some confusion, but its fine now,

**Pull request closed without merging**
