### PR TITLE
Fixed website Address in Readme

### PR DESCRIPTION
**Pull request by viraldevpb**
Hello, @harshita2216 I have solved issue #85! 
_Could you please check this PR and merge it into the main branch if it's correct._

**Issue** - Website correct address is not present in the readme file
**Fixed** - Website address in the readme.md File

### CODE REVIEW

**Review by amanjha8100 — CHANGES_REQUESTED** [review]
You please add your myvenv in .gitignore file, you can see that it has also appeared in your PR.

**Comment by amanjha8100** [comment]
If you need more clarification contact me on project channel.

**Comment by viraldevpb** [comment]
How can I add myvenv environment in .gitignore file?
Can I add this by using env/myvenv this in gitignore.

**Comment by viraldevpb** [comment]
Is this Correct? or I delete the env/ then add my virtual environment name?
dis

**Comment by amanjha8100** [comment]
Just add myvenv/ in . gitignore and create a new PR, the thing is you have changed only one file but because of virtual env it shows 500 plus files chanaged. This is not right.

**Comment by viraldevpb** [comment]
OK, Got it !
I will do this Tommorow Onwards.
Thanks for Replying :)

**Pull request closed without merging**
