### PR TITLE
Added form validaions and success/error message in contact

### PR DESCRIPTION
**Pull request by arpit456jain**
There was no form validations and success/error message in contact us page.
I had added form validations in it and error/success message by the use of message framework of Django
I am attaching a video for better understanding of my changes and result.

https://user-images.githubusercontent.com/55352601/112287642-982bb280-8cb2-11eb-96a1-94eb4e5d4f39.mp4

This PR will lead to close issue  #111 
@harshita2216  mam Please Review it. Thank You

### CODE REVIEW

**Comment by arpit456jain** [comment]
Please add Label of Gssoc'21 before merging it as i am a gssoc'21 participant

**Review by harshita2216 — APPROVED** [review]

**Comment by arpit456jain** [comment]
Thank you @harshita2216 mam

**Comment by arpit456jain** [comment]
@harshita2216 mam please merge it if possible.

**Comment by harshita2216** [comment]
PRs will be merged by Project Admin only. @arpit456jain

**Comment by arpit456jain** [comment]
@harshita2216 mam should I have to mention them. or just wait ?

**Comment by arpit456jain** [comment]
@chiraag-kakar sir please review It.

**Comment by arpit456jain** [comment]
> @chiraag-kakar sir please review It.

@chiraag-kakar kindly review it once

**Comment by arpit456jain** [comment]
@harshita2216 what does it mean branch master is merge into arpitbranch ?😅

**Comment by AVS18** [comment]
@chiraag-kakar please merge this

**Comment by arpit456jain** [comment]
@chiraag-kakar please review this PR its been 20 days . If this PR is not eligible for merging kindly close the PR and issue . I do not mind . but at least review it once.

**Pull request merged**
