### PR TITLE
Added preloader

### LINKED ISSUE #129: Preloader
I want to add a preloader for this project.
I am a gssoc'21 participant and want to contribute on this project.

### PR DESCRIPTION
**Pull request by SnehaVeerakumar**
##Desciption
Added preloader for the website. 

##Fixes
#129 

##Working Video
https://1drv.ms/v/s!AhQCqna6zNwBjiiNJwktCYepQU8w?e=yciURU

### CODE REVIEW

**Comment by SnehaVeerakumar** [comment]
@harshita2216  Kindly review and leave the feedback if any.

**Review by harshita2216 — CHANGES_REQUESTED** [review]
Looks great, just a minor change. Could you please match the color to the color palette? @SnehaVeerakumar

**Comment by SnehaVeerakumar** [comment]
> Looks great, just a minor change. Could you please match the color to the color palette? @SnehaVeerakumar

Oh yeah sure

Blue shades would be fine, right?

**Comment by SnehaVeerakumar** [comment]
Screenshot (1051)

**Comment by SnehaVeerakumar** [comment]
@harshita2216  you can also choose 2 colors and sugggest me :)
If this is fine, I will commit the changes

**Comment by harshita2216** [comment]
> @harshita2216 you can also choose 2 colors and sugggest me :)
> If this is fine, I will commit the changes

#05668d , #d1d8e0

**Comment by SnehaVeerakumar** [comment]
@harshita2216  All done !!

**Review by harshita2216 — APPROVED** [review]

**Pull request merged**
