### PR TITLE
Show on screen errors or messages instead of js alerts  issue: #121

### PR DESCRIPTION
**Pull request by akshay399**
whenever there was some message the site used to pop up an alert like this
image

i changed that to onscreen message like this, saving a click of user and maintaining the flow
image

Share N Learn - Google Chrome 28-03-2021 08_27_42

Share N Learn - Google Chrome 28-03-2021 08_28_46

### CODE REVIEW

**Comment by harshita2216** [comment]
Please update your comment with a brief description and screenshots. @akshay399

**Comment by akshay399** [comment]
> Please update your comment with a brief description and screenshots. @akshay399

ok on it, thanks

**Comment by akshay399** [comment]
> Please update your comment with a brief description and screenshots. @akshay399

ok done, please review it @harshita2216 , thank you

**Comment by akshay399** [comment]
> > Please update your comment with a brief description and screenshots. @akshay399
> 
> ok done, please review it @harshita2216 , thank you

Hi @harshita2216 please review this and inform me the changes if any

**Pull request merged**
